### ISSUE TITLE
not support writing union types as X | Y

### ISSUE THREAD

**Issue by se7enXF** [python-ffmpegio/python-namedpipe#2]
https://github.com/python-ffmpegio/python-namedpipe/blob/a9e9c6ee37dd3f4b51c4531ba85cf48f96d73379/src/namedpipe/_win32.py#L47

Since the python version of this package requires>=3.7, union types need to replace as old style `Union[X,Y]`.

**Comment by tikuma-lsuhsc** [comment]
@se7enXF - Thank you for bring it up. You're right. I should drop 3.7 from the supported version, but it's still avail on 3.8 either. Will fix it soon.

**Comment by tikuma-lsuhsc** [comment]
Resolved on v0.1.1
